#!/usr/bin/env bash
#Scripts that Create a configuration file for redirection
sudo apt update
sudo apt install -y nginx

sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    listen [::]:80;

    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 301 /index.html;
    }
}
EOF'

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

sudo nginx -t

sudo systemctl reload nginx
