#!/usr/bin/env bash
#Scripts that create a custom 404 page
sudo apt update
sudo apt install -y nginx

sudo bash -c 'cat <<EOF > /usr/share/nginx/html/404.html
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>
EOF'

sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/custom_404
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    location / {
        return 301 /index.html;
    }
}
EOF'

sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

sudo nginx -t

sudo systemctl reload nginx

