#!/usr/bin/env bash
#Dealing With Load Balancer setup 
sudo apt-get update
sudo apt-get install -y nginx
var=$(hostname)
sudo chown "$USER":"$USER" /var/www/
sudo chmod -R 777 /var/www
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "46i \\\tadd_header X-Served-By $var;" /etc/nginx/sites-available/default
sudo service nginx restart
~                                                                                                                                                     
~                                                                                                                                                     
~                                                                                                                                                     
~                              
