#!/usr/bin/env bash
#Installing HAproxy to a server
# Install and configure HAproxy on your lb-01 server                          
sudo apt-get update
sudo apt-get install haproxy=2.0.\*
sudo chown "$USER":"$USER" ~/
sudo chmod -R 777 /etc/haproxy

sed -i "$ a\frontend myfrontendsys\n\tbind :80\n\tmode http\n\tdefault_backend my_servers"  /etc/haproxy/haproxy.cfg
sed -i "$ a\backend myservers\n\tbalance roundrobin\n\tserver 480015-web-01 54.237.43.71 check\n\tserver 480015-web-02 52.87.222.69 check" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
~                                                                                                                                                     
~                                                                                                                                                     
~                                                                                                                                                     
~                     
