#!/usr/bin/env bash

# Define signal handlers
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGTERM

# Get current PID and write it to a file
echo $$ > /var/run/myscript.pid

# Display messages indefinitely
while :
do
    echo "To infinity and beyond"
    sleep 1
done
