#!/usr/bin/env bash
#Bash scripts that print "Best School" 10 times and 
#on the 9th times print "hi"

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then 
		echo "hi"
	fi
	echo "Best School"

	((i++))
done
