#!/usr/bin/env bash
#Bash scripts that prints strings at certian index

i=0

while [ $i -lt 20 ]
do 
	((i++))
	case $i in
		5)
			echo "bad luck from China";;
		10)
			echo "bad luck from Japan";;
		18)
			echo "bad luck from Italy";;
	esac
	echo $i
done		
