#!/usr/bin/env bash
#Scripts that deals with update and resolve localhost address

if grep -q docker /proc/1/cgroup; then
    sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
    sudo sed -i 's/facebook.com/8.8.8.8 facebook.com/' /etc/hosts
fi
