#!/usr/bin/env bash
#Scripts that deals with update and resolve localhost address

sudo sed -i 's/127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/facebook\.com[[:space:]]\+[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+/8.8.8.8 facebook.com/' /etc/hosts
